#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


if test $run_gs = false ; then
    echo -e "(I) Gate sizing is turned off.\n"
    exit
fi

ICCAD_PARM='ICCAD15.parm'

for bench in "${these_benches[@]}"
do
    early_lib_name="${bench}_Early.lib"
    late_lib_name="${bench}_Late.lib"
    lef_name="${bench}.lef"

    early_lib="${bench_dir}/${bench}/${early_lib_name}"
    late_lib="${bench_dir}/${bench}/${late_lib_name}"
    lef="${bench_dir}/${bench}/${lef_name}"
    sdc=${bench_dir}/${bench}/${bench}.sdc

	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${these_placers[@]}"
        do
            for sizer in "${these_sizers[@]}"
            do
                base_name=${bench}.${scenario}.${placer}
                out_dir="timing/${bench}.${scenario}.${placer}.${sizer}"

                if [ -d ${out_dir} ]; then
                    rm -rf ${out_dir}
                fi
                mkdir -p ${out_dir}/out

                # library
                ln -s $early_lib ${out_dir}/$early_lib_name
                ln -s $late_lib ${out_dir}/$late_lib_name
                ln -s $lef ${out_dir}/$lef_name

                # Design
                sizing_output="${sizing_dir}/${bench}.${scenario}.${placer}.${sizer}/${bench}_sizing.v"
                def="${write_def_dir}/${bench}.${scenario}.${placer}/${bench}.def"
       
                # Path
                echo $sizing_output
                ln -s ${sizing_output} ${out_dir}/${bench}.v
                ln -s ${def} ${out_dir}/${bench}.def
                ln -s ${sdc} ${out_dir}/${bench}.sdc

                # Create iccad file
                iccad_file=${out_dir}/${bench}.iccad
                echo "${bench}.v ${bench}.def ${bench}.sdc $early_lib_name $late_lib_name $lef_name" \
                > $iccad_file

                # Run
                cmd="./iccad2015_evaluate_solution $ICCAD_PARM $iccad_file $utilization"
                echo $cmd
                $cmd | tee ${base_name}.log.txt

                # Move output files
                rm -f uitimer.tr

                gnuplot ${bench}_grid.plt
                mv *.png ${out_dir}/out

                mv ${base_name}.log.txt ${out_dir}/out
                mv ${bench}_critical.log ${out_dir}/out
                mv ${bench}_critical.plt ${out_dir}/out
                mv *.spef ${out_dir}/out/${bench}.spef
                mv *.tau2015 ${out_dir}/out/${bench}.tau2015
                mv *.timing ${out_dir}/out/${bench}.timing
                mv ${bench}_grid.plt ${out_dir}/out
                mv ${bench}.ops ${out_dir}/out

                if [ -f check_legality.log ]; then
                    mv check_legality.log ${out_dir}/out
                fi
                #mv ${bench}* ${out_dir}/out

                echo ""
                echo ""
            done
        done
    done
done
