#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


if test $run_gs = false ; then
    echo -e "(I) Gate sizing is turned off.\n"
    exit
fi

echo ""
echo "================================================================================"
echo "          _____     __        _____     _          "
echo "         / ___/__ _/ /____   / __(_)__ (_)__  ___ _"
echo "        / (_ / _ \`/ __/ -_) _\ \/ /_ // / _ \/ _ \`/"
echo "        \___/\_,_/\__/\__/ /___/_//__/_/_//_/\_, / "
echo "                                            /___/  "
echo "================================================================================"
echo ""

for bench in "${these_benches[@]}"
do
	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${these_placers[@]}"
        do
            for sizer in "${these_sizers[@]}"
            do
                log_name=${bench}.${sizer}.log.txt

                # ABC output verilog file
                final_verilog="${final_verilog_dir}/${bench}.${scenario}/${bench}.v"

                # Check whether tie cells exist
                cmd="python3 ../utils/400_check_tie_cells.py -i ${final_verilog}"
                echo $cmd; $cmd

                if [ $? -eq 1 ]; then
                    echo "(E) USizer doesn't support Verilog netlist including tie cell(s)."
                    echo "(E) Quitting..."
                    echo ""
                else
                    verilog=${bench}.v
                    sdc=${bench}.sdc
                    spef=${bench}.spef
                    lib=${bench}_Late.lib
                    out_dir=sizing/${bench}.${scenario}.${placer}.${sizer}

                    ln -s ${final_verilog}                                          # Verilog
                    ln -s ${bench_dir}/${bench}/${sdc}                              # SDC
                    ln -s ${timing_dir}/${bench}.${scenario}.${placer}/out/${spef}  # SPEF
                    ln -s ${bench_dir}/${bench}/$lib                                # Liberty
                    # Liberty
                    sizer_lib="${bench_dir}/${bench}/${bench}_Late.lib"
                    ln -s $sizer_lib

                    # Run sizer
                    cmd="./run_sizer.sh ${verilog} ${sdc} ${spef} ${lib} ${sizer} ${out_dir}"
                    echo $cmd; 
                    $cmd | tee $log_name

                    # Move output files
                    sizing_output=${bench}_sizing.v
                    if [ -d "$out_dir" ]; then
                        rm -rf $out_dir
                    fi
                    mkdir $out_dir

                    mv ${bench}* ${out_dir}/
                    if [ $sizer == "USizer2012" ]
                    then
                        mv usizer.config ${out_dir}
                        mv usizer_usizer.v ${out_dir}/${sizing_output}
                        mv lib-characterization-le.report ${out_dir}
                    fi
                    if [ $sizer == "USizer2013" ]
                    then
                        mv usizer.config ${out_dir}
                        mv usizer_usizer.v ${out_dir}/${sizing_output}
                    fi
                fi
                echo ""
                echo ""
            done
        done
    done
done

