#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


echo ""
echo "================================================================================"
echo "           ______                   __               _          "
echo "          / __/ /__  ___  _______  / /__ ____  ___  (_)__  ___ _"
echo "         / _// / _ \/ _ \/ __/ _ \/ / _ \`/ _ \/ _ \/ / _ \/ _ \`/"
echo "        /_/ /_/\___/\___/_/ / .__/_/\_,_/_//_/_//_/_/_//_/\_, / "
echo "                           /_/                           /___/  "
echo "================================================================================"
echo ""

for bench in "${these_benches[@]}"
do
    lef="${bench_dir}/${bench}/${bench}.lef"

	for scenario in "${these_scenarios[@]}"
	do
        final_verilog="${final_verilog_dir}/${bench}.${scenario}/${bench}.v"

        echo "Verilog netlist: ${final_verilog}"
        echo "--------------------------------------------------------------------------------"
        cmd="./run_fp.sh ${bench}"
        cmd="$cmd ${final_verilog} ${lef} ${clock_name} ${utilization}"
        echo $cmd
        $cmd | tee ${bench}.log.txt

        out_dir="bookshelf/${bench}.${scenario}"
        if [ -d $out_dir ]; then
            rm -rf $out_dir
        fi

        mkdir -p ${out_dir}
        mv ${bench}* ${out_dir}
	done
done

