#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


if test $run_gs = false ; then
    echo "(I) Gate sizing is turned off."
    exit
fi

for bench in "${these_benches[@]}"
do
	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${placers[@]}"
        do
            for sizer in "${sizers[@]}"
            do
                log=${bench}.log.txt

                lef="${bench_dir}/${bench}/${bench}.lef"
                initial_def="${initial_def_dir}/${bench}.${scenario}/${bench}.def"
                sizing_output="${sizing_dir}/${bench}.${scenario}.${placer}.${sizer}/${bench}_sizing.v"
                placement="${sizer_legalization_dir}/${bench}.${scenario}.${placer}.${sizer}.FastPlace/${bench}_FP_dp.pl"
                out_def=${bench}.def

                echo "Write DEF from ${placement}"
                echo "--------------------------------------------------------------------------------"
                cmd="python3 ../utils/310_write_def.py --pl ${placement}"
                cmd="$cmd --lef ${lef} --def ${initial_def} --verilog ${sizing_output}"
                cmd="$cmd --def_out ${out_def}"

                echo $cmd
                $cmd | tee ${bench}.${scenario}.${placer}.log

                out_dir="def/${bench}.${scenario}.${placer}.${sizer}.FastPlace"
                if [ -d "$out_dir" ]; then
                    rm -rf $out_dir
                fi
                mkdir -p $out_dir
                mv ${bench}* ${out_dir}
            done
        done
    done
done
