#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


if test $run_gs = false ; then
    echo -e "(I) Gate sizing is turned off.\n"
    exit
fi

for bench in "${these_benches[@]}"
do
	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${these_placers[@]}"
        do
            for sizer in "${these_sizers[@]}"
            do
                log=${bench}.log.txt

                legalization_dir="placement/${bench}.${scenario}.${placer}.${sizer}.FastPlace"

                if [ -d "$legalization_dir" ]; then
                    rm -rf $legalization_dir
                fi
                mkdir ${legalization_dir}
                cd ${legalization_dir}

                bookshelf_dir="${sizer_bookshelf_dir}/${bench}.${scenario}.${placer}.${sizer}"
                ln -s ${bookshelf_dir}/${bench}.nodes
                ln -s ${bookshelf_dir}/${bench}.pl
                ln -s ${bookshelf_dir}/${bench}.aux
                ln -s ${bookshelf_dir}/${bench}.nets
                ln -s ${bookshelf_dir}/${bench}.scl
                ln -s ${bookshelf_dir}/${bench}.wts

                # Legalization using FastPlace3.0
                cmd="../../../bin/FastPlace3.0_Linux64_DP -legalize -fast"
                cmd="$cmd . ${bench}.aux . ${bench}.pl"
                echo $cmd
                eval $cmd | tee ${log}

                # Plotting
                cmd="python3 ../../../utils/300_placement_plotter.py"
                cmd="$cmd --nodes ${bench}.nodes"
                cmd="$cmd --pl ${bench}_FP_dp.pl"
                cmd="$cmd --scl ${bench}.scl"
                echo $cmd
                $cmd
                gnuplot out.plt
                mv out.plt ${bench}_${scenario}_${placer}_${sizer}.plt
                mv out.png ${bench}_${scenario}_${placer}_${sizer}.png
                gzip *.plt
                cd ../../
            done
        done
    done
done
