#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


for bench in "${these_benches[@]}"
do
	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${these_placers[@]}"
        do
            aux="${floorplan_dir}/bookshelf-${bench}.${scenario}/${bench}.aux"

            pl=${bench}.solution.pl

            lef="${bench_dir}/${bench}/${bench}.lef"
            final_verilog="${final_verilog_dir}/${bench}.${scenario}/${bench}.v"
            initial_def="${initial_def_dir}/${bench}.${scenario}/${bench}.def"
            placement="${placement_dir}/${bench}.${scenario}.${placer}/${pl}"
            out_def=${bench}.def

            echo "Write DEF from ${placement}"
            echo "--------------------------------------------------------------------------------"
            cmd="python3 ../utils/310_write_def.py --pl ${placement}"
            cmd="$cmd --lef ${lef} --def ${initial_def} --verilog ${final_verilog}"
            cmd="$cmd --def_out ${out_def}"

            echo $cmd
            $cmd | tee ${bench}.${scenario}.${placer}.log.txt

            out_dir="def/${bench}.${scenario}.${placer}"
            if [ -d $out_dir ]; then
                rm -rf $out_dir
            fi

            mkdir -p ${out_dir}
            mv ${bench}* ${out_dir}
        done
	done
done
