#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1


echo ""
echo "================================================================================"
echo "           ___  __                            __   "
echo "          / _ \/ /__ ________ __ _  ___ ___  / /_  "
echo "         / ___/ / _ \`/ __/ -_)  ' \/ -_) _ \/ __/  "
echo "        /_/  /_/\_,_/\__/\__/_/_/_/\__/_//_/\__/   "
echo ""
echo "================================================================================"
echo ""

mkdir -p placement

for bench in "${these_benches[@]}"
do
	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${these_placers[@]}"
        do
            echo $placer
            source ~/.bashrc
            bookshelf_dir=${floorplan_dir}/${bench}.${scenario}
            out_dir="placement/${bench}.${scenario}.${placer}"
            cmd="./run_place.sh ${bench} ${bookshelf_dir} ${placer} ${target_density} ${out_dir}"
            echo $cmd
            $cmd | tee ${bench}.place.log.txt

            mv ${bench}.place.log.txt ${out_dir}
        done
	done
done

rm -f seeds.out
