#!/bin/bash
# possible calls: run_suite [my_suite|tau|test]

source ../000_config/setup.sh $1

echo ""
echo "================================================================================"
echo "           ___  __                            __   "
echo "          / _ \/ /__ ________ __ _  ___ ___  / /_  "
echo "         / ___/ / _ \`/ __/ -_)  ' \/ -_) _ \/ __/  "
echo "        /_/  /_/\_,_/\__/\__/_/_/_/\__/_//_/\__/   "
echo ""
echo "================================================================================"
echo ""

mkdir -p placement
CUR_DIR=`pwd`

for bench in "${these_benches[@]}"
do
	for scenario in "${these_scenarios[@]}"
	do
        for placer in "${these_placers[@]}"
        do
            echo $placer
            source ~/.bashrc
            bookshelf_dir=${floorplan_dir}/${bench}.${scenario}
            out_dir="placement/${bench}.${scenario}.${placer}"
            cmd="./run_place.sh ${bench} ${bookshelf_dir} ${placer} ${target_density} ${out_dir}"
            echo $cmd
            $cmd | tee ${bench}.place.log.txt

            mv ${bench}.place.log.txt ${out_dir}

            out_name="${bench}.${scenario}.${placer}"
            ln -s ${bench}.solution.pl ${out_dir}/${out_name}.pl

            # Generate a placement plot
            cd $out_dir
            cmd="python3 ${CUR_DIR}/../utils/300_placement_plotter.py"
            cmd="$cmd --nodes ${bookshelf_dir}/${bench}.nodes --scl ${bookshelf_dir}/${bench}.scl"
            cmd="$cmd --pl ${out_name}.pl --out out"
            echo $cmd; eval $cmd
            gnuplot out.plt
            mv out.plt ${out_name}.plt
            mv out.png ${out_name}.png

            cd $CUR_DIR
        done
	done
done

rm -f seeds.out
